#!/bin/bash

# timeouts can be specified via environment or configured here
# NOTE: --timer is additive rather than absolute
[[ ! "$TIMEOUT_LBRT" ]] && TIMEOUT_LBRT=300 # 5min
[[ ! "$TIMEOUT_LOCK" ]] && TIMEOUT_LOCK=300 # 10min (15min)
[[ ! "$TIMEOUT_DPMS" ]] && TIMEOUT_DPMS=300 # 15min (30min)
[[ ! "$TIMEOUT_SUSP" ]] && TIMEOUT_SUSP=900 # 45min (75min)

# run xrandr command for all active outputs
xrandr_cmd() {
	echo "while read out; do xrandr --output \"\$out\" $@;" \
		"done < <(xrandr | grep -Po '^.+(?= connected)')"
}

# generate a dbus-send method call command
# $0 = <0|1>  | use system bus
# $1 = object | dbus object
# $2 = method | method to call
# $@ = [args] | call arguments
dbus_cmd() {
	# extract required parameters
	system="$1"
	object="$2"
	method="$3"
	shift 3

	# system must be 0 or 1
	[[ "$system" != 0 && "$system" != 1 ]] && return 1

	# object and method must exist
	[[ ! "$object" || ! "$method" ]] && return 1

	# --print-reply is necessary or the method won't be run (bug?)
	echo "dbus-send $([[ "$system" -eq 1 ]] && echo '--system ')" \
		"--print-reply" \
		"--dest=\"${object}\" \"/${object//./\/}\"" \
		"\"${object}.${method}\" $@ &>/dev/null"
}

# disable the default X11 behavior (re-enabled by systemd unit)
xset s noblank s noexpose -dpms

# run xidlehook
exec xidlehook \
	--detect-sleep \
	--not-when-fullscreen \
	--not-when-audio \
	--timer "$TIMEOUT_LBRT" \
		"$(xrandr_cmd --brightness .5)" \
		"$(xrandr_cmd --brightness 1)" \
	--timer "$TIMEOUT_LOCK" \
		"$(xrandr_cmd --brightness .1);$(dbus_cmd 0 org.freedesktop.ScreenSaver Lock)" \
		"$(xrandr_cmd --brightness 1)" \
	--timer "$TIMEOUT_DPMS" \
		"xset dpms force standby" \
		"$(xrandr_cmd --brightness 1)" \
	--timer "$TIMEOUT_SUSP" \
		"$(dbus_cmd 1 org.freedesktop.login1 Manager.Suspend boolean:true)" \
		"$(xrandr_cmd --brightness 1); xset s noblank s noexpose -dpms"
